services:
  user-service:
    build: ./user-service
    volumes:
      - ./user-service:app
    ports:
      - 8000:8000
    command: python manage.py runserver 0.0.0.0:8000
    container_name: userService
    depends_on:
      - user-db

  user-db:
      image: postgres:15
      env_file:
        - user-service/.env.user
      environment:
        POSTGRES_DB: ${DB_NAME}
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}

      ports:
        - "5432:5432"
      volumes:
        - user_pgdata:/var/lib/postgresql/data

volumes:
  user_pgdata:

