# Generated by Django 5.2 on 2025-06-20 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('bio', models.CharField(blank=True, max_length=200, null=True)),
                ('saved_searches', models.JSONField(blank=True, null=True)),
                ('wishlist', models.JSONField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], null=True)),
                ('Date_of_birth', models.DateField(blank=True, null=True)),
                ('notification_preferences', models.JSONField(blank=True, default=dict, help_text='Notification preferences', null=True, verbose_name='Notification Preferences')),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verified_poster', models.BooleanField(default=False, help_text='Whether the poster is verified or not')),
                ('poster_verification_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('poster_documents', models.JSONField(blank=True, help_text='Documents uploaded by the poster', null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_validated',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Designates whether the user has verified their email address.'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('owner', 'Owner'), ('manager', 'Manager'), ('admin', 'Admin'), ('agent', 'Agent'), ('tenant', 'Tenant')], default='user', max_length=20),
        ),
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.userprofile')),
                ('license_id', models.CharField(blank=True, max_length=20, null=True)),
                ('license_expiration_date', models.DateField(blank=True, null=True)),
                ('license_documents', models.JSONField(blank=True, help_text='Documents uploaded by the agent', null=True)),
                ('clients_managed_count', models.PositiveIntegerField(default=0)),
                ('agency_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            bases=('accounts.userprofile',),
        ),
        migrations.CreateModel(
            name='ManagerProfile',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.userprofile')),
                ('properties_managed_count', models.PositiveIntegerField(default=0)),
                ('assigned_properties', models.JSONField(blank=True, help_text='Properties managed by the manager', null=True)),
                ('maintainces_requests_handled_count', models.PositiveIntegerField(default=0)),
                ('assigned_maintainces_requests', models.JSONField(blank=True, help_text='Maintainces requests handled by the manager', null=True)),
            ],
            bases=('accounts.userprofile',),
        ),
        migrations.CreateModel(
            name='OwnerProfile',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.userprofile')),
                ('ownership_documents', models.JSONField(blank=True, help_text='Documents uploaded by the owner', null=True)),
                ('properties_owned_count', models.PositiveIntegerField(default=0)),
            ],
            bases=('accounts.userprofile',),
        ),
        migrations.CreateModel(
            name='TenantProfile',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.userprofile')),
                ('tenant_documents', models.JSONField(blank=True, help_text='Documents uploaded by the tenant', null=True)),
                ('properties_rented_count', models.PositiveIntegerField(default=0)),
                ('rental_history_rating', models.PositiveIntegerField(default=0)),
                ('preferred_locations', models.JSONField(blank=True, help_text='Preferred locations for renting', null=True)),
            ],
            bases=('accounts.userprofile',),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
